import { NAME } from './constants'

export const FETCH_POKEMON = `${NAME}/FETCH_POKEMON`
export const FETCH_POKEMON_SUCCESS = `${NAME}/FETCH_POKEMON_SUCCESS`
export const FETCH_POKEMON_FAILURE = `${NAME}/FETCH_POKEMON_FAILURE`

export const SET_ACTIVE_POKEMON_ID = `${NAME}/SET_ACTIVE_POKEMON_ID`

