import { NAME } from './constants'

export const FETCH_POKEMONS = `${NAME}/FETCH_POKEMONS`
export const FETCH_POKEMONS_SUCCESS = `${NAME}/FETCH_POKEMONS_SUCCESS`
export const FETCH_POKEMONS_FAILURE = `${NAME}/FETCH_POKEMONS_FAILURE`

export const OPEN_PANEL = `${NAME}/OPEN_PANEL`
export const CLOSE_PANEL = `${NAME}/CLOSE_PANEL`
